exception opening subject list file
Traceback (most recent call last):
  File "cinabox.py", line 238, in <module>
    count_subjects()
  File "cinabox.py", line 179, in count_subjects
    for line in f.readlines():
UnboundLocalError: local variable 'f' referenced before assignment
umount: /dev/sda1: not found
mke2fs 1.41.12 (17-May-2010)
umount: /dev/sdb1: not mounted
mke2fs 1.41.12 (17-May-2010)
